server:
  port: 8070
  servlet:
    context-path: /springbootpracticeExample

spring:
  application:
    name: practice-client
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: priyanka@12650
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

message:
  userMessage: Hello World from Developers
  displayMessage: Dev Display